# This is a basic workflow to help you get started with Actions
name: Go Test
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        go_version: [1.14.x]
        platform: [ubuntu-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }} 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go_version: ${{ matrix.go_version }}
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Format
        run: echo "valid if the command returns some value from GoFMT" && [ -z $(shell gofmt -l . | grep ".go") ] && true || false
      - name: Security
        run: go get github.com/securego/gosec/cmd/gosec; `go env GOPATH`/bin/gosec ./...
      - name: Testing
        run:  go test -v ./...
